# Generated by Django 2.2.6 on 2020-09-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiciosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ubicacion',
            field=models.URLField(blank=True, null=True, verbose_name='Página Web'),
        ),
        migrations.AddField(
            model_name='historicalempresa',
            name='ubicacion',
            field=models.URLField(blank=True, null=True, verbose_name='Página Web'),
        ),
        migrations.AddField(
            model_name='historicalhospital',
            name='ubicacion',
            field=models.URLField(blank=True, null=True, verbose_name='Página Web'),
        ),
        migrations.AddField(
            model_name='historicalhoteles',
            name='ubicacion',
            field=models.URLField(blank=True, null=True, verbose_name='Página Web'),
        ),
        migrations.AddField(
            model_name='historicalrestaurant',
            name='ubicacion',
            field=models.URLField(blank=True, null=True, verbose_name='Página Web'),
        ),
        migrations.AddField(
            model_name='historicalunidadeducativa',
            name='ubicacion',
            field=models.URLField(blank=True, null=True, verbose_name='Página Web'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ubicacion',
            field=models.URLField(blank=True, null=True, verbose_name='Página Web'),
        ),
        migrations.AddField(
            model_name='hoteles',
            name='ubicacion',
            field=models.URLField(blank=True, null=True, verbose_name='Página Web'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='ubicacion',
            field=models.URLField(blank=True, null=True, verbose_name='Página Web'),
        ),
        migrations.AddField(
            model_name='unidadeducativa',
            name='ubicacion',
            field=models.URLField(blank=True, null=True, verbose_name='Página Web'),
        ),
    ]
