# Generated by Django 2.2.6 on 2020-09-09 15:06

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ServiciosApp', '0002_auto_20200903_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=90, verbose_name='Título')),
                ('imagen', models.ImageField(upload_to='empresas')),
                ('estado', models.BooleanField(default=True, verbose_name='Publicado/No publicado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicado',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=90, verbose_name='Título')),
                ('imagen', models.ImageField(upload_to='empresas')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Página Web')),
                ('estado', models.BooleanField(default=True, verbose_name='Publicado/No publicado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticia',
            },
        ),
        migrations.AlterField(
            model_name='empresa',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ubicacion',
            field=models.URLField(blank=True, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='ubicacion',
            field=models.URLField(blank=True, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='historicalhospital',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='historicalhospital',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhospital',
            name='ubicacion',
            field=models.URLField(blank=True, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='historicalhoteles',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='historicalhoteles',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhoteles',
            name='ubicacion',
            field=models.URLField(blank=True, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='historicalrestaurant',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='historicalrestaurant',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrestaurant',
            name='ubicacion',
            field=models.URLField(blank=True, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='historicaltransporte',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalunidadeducativa',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='historicalunidadeducativa',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='ubicacion',
            field=models.URLField(blank=True, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='hoteles',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='hoteles',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoteles',
            name='ubicacion',
            field=models.URLField(blank=True, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='ubicacion',
            field=models.URLField(blank=True, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadeducativa',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='unidadeducativa',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalNoticia',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('nombre', models.CharField(max_length=90, verbose_name='Título')),
                ('imagen', models.TextField(max_length=100)),
                ('web', models.URLField(blank=True, null=True, verbose_name='Página Web')),
                ('estado', models.BooleanField(default=True, verbose_name='Publicado/No publicado')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Noticia',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalComunicado',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('nombre', models.CharField(max_length=90, verbose_name='Título')),
                ('imagen', models.TextField(max_length=100)),
                ('estado', models.BooleanField(default=True, verbose_name='Publicado/No publicado')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Comunicado',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
