# Generated by Django 2.2.6 on 2020-08-18 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='tutulo',
            new_name='titulo',
        ),
    ]
