# Generated by Django 2.2.6 on 2020-08-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0002_auto_20200817_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(upload_to='proyecto'),
        ),
    ]
