# Generated by Django 2.2.6 on 2020-08-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContenidoApp', '0002_auto_20200820_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestacione',
            name='audio1',
            field=models.FileField(upload_to='manifestaciones'),
        ),
        migrations.AlterField(
            model_name='manifestacione',
            name='imagen1',
            field=models.ImageField(upload_to='manifestaciones'),
        ),
        migrations.AlterField(
            model_name='manifestacione',
            name='imagen2',
            field=models.ImageField(upload_to='manifestaciones'),
        ),
    ]
