# Generated by Django 2.2.6 on 2020-08-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContenidoApp', '0003_auto_20200820_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastronomia',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalgastronomia',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
