# Generated by Django 2.2.6 on 2020-09-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContenidoApp', '0004_auto_20200831_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballet',
            name='imagen',
            field=models.FileField(upload_to='ballet'),
        ),
    ]
